# Generated by Django 4.0.6 on 2022-07-28 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mlModel', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='dataSet',
            fields=[
                ('testID', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=30, null=True)),
                ('datasetFile', models.FileField(upload_to='')),
                ('selectModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.mlmodelcategory')),
            ],
        ),
    ]
